package view.administrar;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.UIManager;

public class VAdministrador extends javax.swing.JDialog {

    public static int opcion;

    public VAdministrador(JFrame v, boolean modal) {
        super(v, modal);
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Error al inicializar FlatLaf");
        }
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/view/img/peda.png")).getImage());
        setLocationRelativeTo(this);

        //OCULTAR BTN DE ELIMINAR
        getBTN_ELIMINARDIRECTORGENERAL().setVisible(false);
        getBTN_ELIMINARDIRECTORRRHH().setVisible(false);
        getBTN_ELIMINARUSUARIO().setVisible(false);

        DecorarJtablet(jTable_HISTORIAL);
        DecorarJtablet(jTable_DIRECTORGENERAL);
        DecorarJtablet(jTable_USUARIOS);
        DecorarJtablet(jTable_DIRECTORRRHH);
    }

    private void DecorarJtablet(JTable jtable) {
        jtable.getTableHeader().setOpaque(false);
        jtable.getTableHeader().setBackground(new Color(102, 102, 102));
        jtable.getTableHeader().setForeground(Color.WHITE);
    }

    public JButton getBTN_ELIMINARDIRECTORGENERAL() {
        return BTN_ELIMINARDIRECTORGENERAL;
    }

    public JButton getBTN_ELIMINARDIRECTORRRHH() {
        return BTN_ELIMINARDIRECTORRRHH;
    }

    public JButton getBTN_ELIMINARUSUARIO() {
        return BTN_ELIMINARUSUARIO;
    }

    public JButton getBTN_NUEVODIRECTORGENERAL() {
        return BTN_NUEVODIRECTORGENERAL;
    }

    public JButton getBTN_NUEVODIRECTORRRHH() {
        return BTN_NUEVODIRECTORRRHH;
    }

    public JButton getBTN_NUEVOUSUARIO() {
        return BTN_NUEVOUSUARIO;
    }

    public JTable getjTable_DIRECTORGENERAL() {
        return jTable_DIRECTORGENERAL;
    }

    public JTable getjTable_DIRECTORRRHH() {
        return jTable_DIRECTORRRHH;
    }

    public JTable getjTable_HISTORIAL() {
        return jTable_HISTORIAL;
    }

    public JTable getjTable_USUARIOS() {
        return jTable_USUARIOS;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_DIRECTORGENERAL = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_HISTORIAL = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_USUARIOS = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_DIRECTORRRHH = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTN_NUEVOUSUARIO = new view.componentes.BTN();
        BTN_ELIMINARUSUARIO = new view.componentes.BTN();
        jPanel3 = new javax.swing.JPanel();
        BTN_NUEVODIRECTORGENERAL = new view.componentes.BTN();
        BTN_ELIMINARDIRECTORGENERAL = new view.componentes.BTN();
        jPanel4 = new javax.swing.JPanel();
        BTN_NUEVODIRECTORRRHH = new view.componentes.BTN();
        BTN_ELIMINARDIRECTORRRHH = new view.componentes.BTN();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADMINISTRAR");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("DIRECTOR GENERAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jTable_DIRECTORGENERAL.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable_DIRECTORGENERAL.setForeground(new java.awt.Color(102, 102, 102));
        jTable_DIRECTORGENERAL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "RANGO", "PRIMER NOMBRE", "SEGUNDO NOMBRE", "PRIMER APELLIDO", "SEGUNDO APELLIDO", "CÉDULA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DIRECTORGENERAL.setRowHeight(24);
        jTable_DIRECTORGENERAL.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable_DIRECTORGENERAL.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jTable_DIRECTORGENERAL);
        if (jTable_DIRECTORGENERAL.getColumnModel().getColumnCount() > 0) {
            jTable_DIRECTORGENERAL.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTable_DIRECTORGENERAL.getColumnModel().getColumn(0).setMaxWidth(1000);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 740, 70));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 870, 0));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("USUARIOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTable_HISTORIAL.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable_HISTORIAL.setForeground(new java.awt.Color(102, 102, 102));
        jTable_HISTORIAL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "FECHA/HORA", "USUARIO", "INFORMACIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_HISTORIAL.setRowHeight(24);
        jTable_HISTORIAL.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable_HISTORIAL.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable_HISTORIAL);
        if (jTable_HISTORIAL.getColumnModel().getColumnCount() > 0) {
            jTable_HISTORIAL.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable_HISTORIAL.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable_HISTORIAL.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable_HISTORIAL.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 860, 160));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 870, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("HISTORIAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jTable_USUARIOS.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable_USUARIOS.setForeground(new java.awt.Color(102, 102, 102));
        jTable_USUARIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°", "USUARIO", "PRIMER NOMBRE", "PRIMER APELLIDO", "CÉDULA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_USUARIOS.setOpaque(false);
        jTable_USUARIOS.setRowHeight(24);
        jTable_USUARIOS.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable_USUARIOS.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable_USUARIOS.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jTable_USUARIOS);
        if (jTable_USUARIOS.getColumnModel().getColumnCount() > 0) {
            jTable_USUARIOS.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTable_USUARIOS.getColumnModel().getColumn(0).setMaxWidth(1000);
        }

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 740, 120));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("DIRECTOR DE RRHH");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, 20));

        jTable_DIRECTORRRHH.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable_DIRECTORRRHH.setForeground(new java.awt.Color(102, 102, 102));
        jTable_DIRECTORRRHH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "RANGO", "PRIMER NOMBRE", "SEGUNDO NOMBRE", "PRIMER APELLIDO", "SEGUNDO APELLIDO", "CÉDULA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DIRECTORRRHH.setRowHeight(24);
        jTable_DIRECTORRRHH.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable_DIRECTORRRHH.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(jTable_DIRECTORRRHH);
        if (jTable_DIRECTORRRHH.getColumnModel().getColumnCount() > 0) {
            jTable_DIRECTORRRHH.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTable_DIRECTORRRHH.getColumnModel().getColumn(0).setMaxWidth(1000);
        }

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 740, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8_no_16px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 10, 5));

        BTN_NUEVOUSUARIO.setBackground(new java.awt.Color(102, 102, 102));
        BTN_NUEVOUSUARIO.setForeground(new java.awt.Color(255, 255, 255));
        BTN_NUEVOUSUARIO.setText("REGISTRAR");
        BTN_NUEVOUSUARIO.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BTN_NUEVOUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NUEVOUSUARIOActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_NUEVOUSUARIO);

        BTN_ELIMINARUSUARIO.setBackground(new java.awt.Color(204, 0, 0));
        BTN_ELIMINARUSUARIO.setForeground(new java.awt.Color(255, 255, 255));
        BTN_ELIMINARUSUARIO.setText("ELIMINAR");
        BTN_ELIMINARUSUARIO.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.add(BTN_ELIMINARUSUARIO);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0, 10, 5));

        BTN_NUEVODIRECTORGENERAL.setBackground(new java.awt.Color(102, 102, 102));
        BTN_NUEVODIRECTORGENERAL.setForeground(new java.awt.Color(255, 255, 255));
        BTN_NUEVODIRECTORGENERAL.setText("REGISTRAR");
        BTN_NUEVODIRECTORGENERAL.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BTN_NUEVODIRECTORGENERAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NUEVODIRECTORGENERALActionPerformed(evt);
            }
        });
        jPanel3.add(BTN_NUEVODIRECTORGENERAL);

        BTN_ELIMINARDIRECTORGENERAL.setBackground(new java.awt.Color(204, 0, 0));
        BTN_ELIMINARDIRECTORGENERAL.setForeground(new java.awt.Color(255, 255, 255));
        BTN_ELIMINARDIRECTORGENERAL.setText("ELIMINAR");
        BTN_ELIMINARDIRECTORGENERAL.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel3.add(BTN_ELIMINARDIRECTORGENERAL);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, -1, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 10, 5));

        BTN_NUEVODIRECTORRRHH.setBackground(new java.awt.Color(102, 102, 102));
        BTN_NUEVODIRECTORRRHH.setForeground(new java.awt.Color(255, 255, 255));
        BTN_NUEVODIRECTORRRHH.setText("REGISTRAR");
        BTN_NUEVODIRECTORRRHH.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BTN_NUEVODIRECTORRRHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NUEVODIRECTORRRHHActionPerformed(evt);
            }
        });
        jPanel4.add(BTN_NUEVODIRECTORRRHH);

        BTN_ELIMINARDIRECTORRRHH.setBackground(new java.awt.Color(204, 0, 0));
        BTN_ELIMINARDIRECTORRRHH.setForeground(new java.awt.Color(255, 255, 255));
        BTN_ELIMINARDIRECTORRRHH.setText("ELIMINAR");
        BTN_ELIMINARDIRECTORRRHH.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel4.add(BTN_ELIMINARDIRECTORRRHH);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void BTN_NUEVOUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NUEVOUSUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_NUEVOUSUARIOActionPerformed

    private void BTN_NUEVODIRECTORGENERALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NUEVODIRECTORGENERALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_NUEVODIRECTORGENERALActionPerformed

    private void BTN_NUEVODIRECTORRRHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NUEVODIRECTORRRHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_NUEVODIRECTORRRHHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.componentes.BTN BTN_ELIMINARDIRECTORGENERAL;
    private view.componentes.BTN BTN_ELIMINARDIRECTORRRHH;
    private view.componentes.BTN BTN_ELIMINARUSUARIO;
    private view.componentes.BTN BTN_NUEVODIRECTORGENERAL;
    private view.componentes.BTN BTN_NUEVODIRECTORRRHH;
    private view.componentes.BTN BTN_NUEVOUSUARIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_DIRECTORGENERAL;
    private javax.swing.JTable jTable_DIRECTORRRHH;
    private javax.swing.JTable jTable_HISTORIAL;
    private javax.swing.JTable jTable_USUARIOS;
    // End of variables declaration//GEN-END:variables
}
