/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.personas;

import com.formdev.flatlaf.FlatLightLaf;
import com.toedter.calendar.JDateChooser;
import evento.otro.TextoMayuscula;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author Dixson
 */
public class VEditarPersona extends javax.swing.JDialog {

    public static String rutaFoto;
    public static int idpersona;
    public static String foto1 = "";

    /**
     * Creates new form Jframe_NUEVOFUNCIONARIO
     */
    public VEditarPersona(JFrame v, boolean modal) {

        super(v, modal);

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Error al inicializar FlatLaf");
        }

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/view/img/peda.png")).getImage());

        setLocationRelativeTo(this);
    }

    public JButton getBTN_FOTO() {
        return BTN_FOTO;
    }

    public JButton getBTN_EDITARPERSONA() {
        return BTN_GUARDAR;
    }

    public JTextField getCedula() {
        return cedula;
    }

    public JTextField getCorreo() {
        return correo;
    }

    public JTextArea getDireccion() {
        return direccion;
    }

    public JComboBox getEstado() {
        return estado;
    }

    public JComboBox<String> getEstadocivil() {
        return estadocivil;
    }

    public JDateChooser getFechanacimiento() {
        return fechanacimiento;
    }

    public JLabel getFoto() {
        return foto;
    }

    public JComboBox<String> getGenero() {
        return genero;
    }

    public JComboBox getGruposanguineo() {
        return gruposanguineo;
    }

    public JTextField getLugarnacimiento() {
        return lugarnacimiento;
    }

    public JTextField getMunicipio() {
        return municipio;
    }

    public JComboBox<String> getNivelacademico() {
        return nivelacademico;
    }

    public JTextField getParroquia() {
        return parroquia;
    }

    public JTextField getPrimerapellido() {
        return primerapellido;
    }

    public JTextField getPrimernombre() {
        return primernombre;
    }

    public JTextField getSegundoapellido() {
        return segundoapellido;
    }

    public JTextField getSegundonombre() {
        return segundonombre;
    }

    public JTextField getTelefono1() {
        return telefono1;
    }

    public JTextField getTelefono2() {
        return telefono2;
    }

    public JTextField getTituloobtenido1() {
        return tituloobtenido1;
    }

    public JTextField getTituloobtenido2() {
        return tituloobtenido2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        direccion = new javax.swing.JTextArea();
        primernombre = new javax.swing.JTextField();
        segundonombre = new javax.swing.JTextField();
        primerapellido = new javax.swing.JTextField();
        segundoapellido = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        parroquia = new javax.swing.JTextField();
        nivelacademico = new javax.swing.JComboBox<>();
        estadocivil = new javax.swing.JComboBox<>();
        genero = new javax.swing.JComboBox<>();
        lugarnacimiento = new javax.swing.JTextField();
        tituloobtenido1 = new javax.swing.JTextField();
        tituloobtenido2 = new javax.swing.JTextField();
        telefono1 = new javax.swing.JTextField();
        telefono2 = new javax.swing.JTextField();
        municipio = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        fechanacimiento = new com.toedter.calendar.JDateChooser();
        estado = new javax.swing.JComboBox<>();
        gruposanguineo = new javax.swing.JComboBox<>();
        BTN_FOTO = new view.componentes.BTN();
        jLabel2 = new javax.swing.JLabel();
        BTN_GUARDAR = new view.componentes.BTN();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRAR");
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDITAR INFORMACIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 526, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 680, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 160, 160));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("- PRIMER NOMBRE:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("- SEGUNDO NOMBRE:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("- PRIMER APELLIDO:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setText("- SEGUNDO APELLIDO:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setText("- CÉDULA DE IDENTIDAD:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel19.setText("- FECHA DE NACIMIENTO:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel21.setText("- LUGAR DE NACIMIENTO:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel24.setText("- ESTADO CIVIL:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel27.setText("- GENERO:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel30.setText("- NIVEL ACADEMICO:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel33.setText("- TITULO OBTENIDO:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel36.setText("- OTRO TITULO:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel39.setText("- TELEFONO:");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel42.setText("- OTRO TELEFONO:");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel45.setText("- GRUPO SANGUINEO:");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 20));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel48.setText("- DIRECCIÓN:");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 20));

        jLabel51.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel51.setText("- ESTADO:");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 20));

        jLabel54.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel54.setText("- MUNICIPIO:");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 20));

        jLabel57.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel57.setText("- PARROQUIA:");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 20));

        direccion.setColumns(20);
        direccion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        direccion.setForeground(new java.awt.Color(102, 102, 102));
        direccion.setLineWrap(true);
        direccion.setRows(5);
        direccion.setWrapStyleWord(true);
        direccion.setBorder(null);
        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                direccionKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(direccion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 310, -1));

        primernombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        primernombre.setForeground(new java.awt.Color(102, 102, 102));
        primernombre.setToolTipText("");
        primernombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        primernombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                primernombreKeyReleased(evt);
            }
        });
        jPanel2.add(primernombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 250, 20));

        segundonombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        segundonombre.setForeground(new java.awt.Color(102, 102, 102));
        segundonombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        segundonombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                segundonombreKeyReleased(evt);
            }
        });
        jPanel2.add(segundonombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 250, 20));

        primerapellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        primerapellido.setForeground(new java.awt.Color(102, 102, 102));
        primerapellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        primerapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                primerapellidoKeyReleased(evt);
            }
        });
        jPanel2.add(primerapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 250, 20));

        segundoapellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        segundoapellido.setForeground(new java.awt.Color(102, 102, 102));
        segundoapellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        segundoapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                segundoapellidoKeyReleased(evt);
            }
        });
        jPanel2.add(segundoapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 250, 20));

        cedula.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cedula.setForeground(new java.awt.Color(102, 102, 102));
        cedula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaKeyTyped(evt);
            }
        });
        jPanel2.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 250, 20));

        parroquia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        parroquia.setForeground(new java.awt.Color(102, 102, 102));
        parroquia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        parroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parroquiaActionPerformed(evt);
            }
        });
        parroquia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parroquiaKeyReleased(evt);
            }
        });
        jPanel2.add(parroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 250, 20));

        nivelacademico.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nivelacademico.setForeground(new java.awt.Color(0, 0, 51));
        nivelacademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO BACHILLER", "BACHILLER", "TÉCNICO MEDIO", "TÉCNICO SUPERIOR UNIVERSITARIO", "LICENCIADO(A)", "INGENIERO(A)", "ABOGADO", "PROFESOR(A)", "MEDICO", "ESPECIALIDAD", "MAGISTER", "DOCTORADO" }));
        jPanel2.add(nivelacademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 260, -1));

        estadocivil.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        estadocivil.setForeground(new java.awt.Color(0, 0, 51));
        estadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTERO(A)", "CASADO(A)", "VIUDO(A)", "CONCUBINATO" }));
        jPanel2.add(estadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 260, -1));

        genero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        genero.setForeground(new java.awt.Color(0, 0, 51));
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel2.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 260, -1));

        lugarnacimiento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lugarnacimiento.setForeground(new java.awt.Color(102, 102, 102));
        lugarnacimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        lugarnacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lugarnacimientoKeyReleased(evt);
            }
        });
        jPanel2.add(lugarnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 250, 20));

        tituloobtenido1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tituloobtenido1.setForeground(new java.awt.Color(102, 102, 102));
        tituloobtenido1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        tituloobtenido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tituloobtenido1KeyReleased(evt);
            }
        });
        jPanel2.add(tituloobtenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 250, 20));

        tituloobtenido2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tituloobtenido2.setForeground(new java.awt.Color(102, 102, 102));
        tituloobtenido2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        tituloobtenido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tituloobtenido2KeyReleased(evt);
            }
        });
        jPanel2.add(tituloobtenido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 250, 20));

        telefono1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        telefono1.setForeground(new java.awt.Color(102, 102, 102));
        telefono1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefono1KeyTyped(evt);
            }
        });
        jPanel2.add(telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 250, 20));

        telefono2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        telefono2.setForeground(new java.awt.Color(102, 102, 102));
        telefono2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        telefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefono2KeyTyped(evt);
            }
        });
        jPanel2.add(telefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 250, 20));

        municipio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        municipio.setForeground(new java.awt.Color(102, 102, 102));
        municipio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        municipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                municipioKeyReleased(evt);
            }
        });
        jPanel2.add(municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 250, 20));

        jLabel46.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel46.setText("- CORREO:");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        correo.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        correo.setForeground(new java.awt.Color(102, 102, 102));
        correo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                correoKeyReleased(evt);
            }
        });
        jPanel2.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 250, 20));

        fechanacimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        fechanacimiento.setForeground(new java.awt.Color(102, 102, 102));
        fechanacimiento.setDateFormatString("dd-MM-yyyy");
        fechanacimiento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.add(fechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 160, -1));

        estado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISTRITO CAPITAL", "AMAZONAS", "ANZOÁTEGUI", "APURE", "ARAGUA", "BARINAS", "BOLÍVAR", "CARABOBO", "COJEDES", "DELTA AMACURO", "FALCÓN", "GUÁRICO", "LA GUAIRA", "LARA", "MÉRIDA", "MIRANDA", "MONAGAS", "NUEVA ESPARTA", "PORTUGUESA", "SUCRE", "TÁCHIRA", "TRUJILLO", "YARACUY", "ZULIA" }));
        estado.setSelectedIndex(9);
        estado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 260, -1));

        gruposanguineo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        gruposanguineo.setForeground(new java.awt.Color(0, 0, 51));
        gruposanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        gruposanguineo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(gruposanguineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 260, -1));

        BTN_FOTO.setBackground(new java.awt.Color(102, 102, 102));
        BTN_FOTO.setForeground(new java.awt.Color(255, 255, 255));
        BTN_FOTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8_pictures_folder_16px.png"))); // NOI18N
        BTN_FOTO.setText("FOTO");
        BTN_FOTO.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.add(BTN_FOTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 160, 30));

        jTabbedPane1.addTab("DATOS PERSONALES", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 680, 560));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8_no_16px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        BTN_GUARDAR.setBackground(new java.awt.Color(102, 102, 102));
        BTN_GUARDAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_GUARDAR.setText("REGISTRAR");
        BTN_GUARDAR.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.add(BTN_GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cedulaKeyTyped

    private void telefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono1KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_telefono1KeyTyped

    private void telefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono2KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_telefono2KeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.foto1 = "";
    }//GEN-LAST:event_formWindowClosed

    private void primernombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primernombreKeyReleased
        TextoMayuscula texto = new TextoMayuscula(primernombre);
        texto.keyReleased(evt);
    }//GEN-LAST:event_primernombreKeyReleased

    private void segundonombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_segundonombreKeyReleased
        TextoMayuscula texto = new TextoMayuscula(segundonombre);
        texto.keyReleased(evt);
    }//GEN-LAST:event_segundonombreKeyReleased

    private void primerapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primerapellidoKeyReleased
        TextoMayuscula texto = new TextoMayuscula(primerapellido);
        texto.keyReleased(evt);
    }//GEN-LAST:event_primerapellidoKeyReleased

    private void segundoapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_segundoapellidoKeyReleased
        TextoMayuscula texto = new TextoMayuscula(segundoapellido);
        texto.keyReleased(evt);
    }//GEN-LAST:event_segundoapellidoKeyReleased

    private void lugarnacimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lugarnacimientoKeyReleased
        TextoMayuscula texto = new TextoMayuscula(lugarnacimiento);
        texto.keyReleased(evt);
    }//GEN-LAST:event_lugarnacimientoKeyReleased

    private void tituloobtenido1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tituloobtenido1KeyReleased
        TextoMayuscula texto = new TextoMayuscula(tituloobtenido1);
        texto.keyReleased(evt);
    }//GEN-LAST:event_tituloobtenido1KeyReleased

    private void tituloobtenido2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tituloobtenido2KeyReleased
        TextoMayuscula texto = new TextoMayuscula(tituloobtenido2);
        texto.keyReleased(evt);
    }//GEN-LAST:event_tituloobtenido2KeyReleased

    private void correoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoKeyReleased
        TextoMayuscula texto = new TextoMayuscula(correo);
        texto.keyReleased(evt);
    }//GEN-LAST:event_correoKeyReleased

    private void municipioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_municipioKeyReleased
        TextoMayuscula texto = new TextoMayuscula(municipio);
        texto.keyReleased(evt);
    }//GEN-LAST:event_municipioKeyReleased

    private void parroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parroquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parroquiaActionPerformed

    private void parroquiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parroquiaKeyReleased
        TextoMayuscula texto = new TextoMayuscula(parroquia);
        texto.keyReleased(evt);
    }//GEN-LAST:event_parroquiaKeyReleased

    private void direccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionKeyReleased
        TextoMayuscula texto = new TextoMayuscula(direccion);
        texto.keyReleased(evt);
    }//GEN-LAST:event_direccionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.componentes.BTN BTN_FOTO;
    private view.componentes.BTN BTN_GUARDAR;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField correo;
    private javax.swing.JTextArea direccion;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JComboBox<String> estadocivil;
    private com.toedter.calendar.JDateChooser fechanacimiento;
    private javax.swing.JLabel foto;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JComboBox<String> gruposanguineo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lugarnacimiento;
    private javax.swing.JTextField municipio;
    private javax.swing.JComboBox<String> nivelacademico;
    private javax.swing.JTextField parroquia;
    private javax.swing.JTextField primerapellido;
    private javax.swing.JTextField primernombre;
    private javax.swing.JTextField segundoapellido;
    private javax.swing.JTextField segundonombre;
    private javax.swing.JTextField telefono1;
    private javax.swing.JTextField telefono2;
    private javax.swing.JTextField tituloobtenido1;
    private javax.swing.JTextField tituloobtenido2;
    // End of variables declaration//GEN-END:variables
}
