/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.personas;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.UIManager;

/**
 *
 * @author Dixson
 */
public class VVerPersona extends javax.swing.JDialog {

    /**
     * Creates new form Jframe_NUEVOFUNCIONARIO
     */
    public VVerPersona(JFrame v, boolean modal) {

        super(v, modal);

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Error al inicializar FlatLaf");
        }
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/view/img/peda.png")).getImage());
        setLocationRelativeTo(this);

        jTextArea_direccion.setEnabled(false);
    }


    public JLabel getcedula() {
        return jLabel_cedula;
    }

    public JLabel getcorreo() {
        return jLabel_correo;
    }

    public JLabel getestado() {
        return jLabel_estado;
    }

    public JLabel getestadocivil() {
        return jLabel_estadocivil;
    }

    public JLabel getfechanacimiento() {
        return jLabel_fechanacimiento;
    }

    public JLabel getfoto() {
        return jLabel_foto;
    }

    public JLabel getgenero() {
        return jLabel_genero;
    }

    public JLabel getlugarnacimiento() {
        return jLabel_lugarnacimiento;
    }

    public JLabel getmunicipio() {
        return jLabel_municipio;
    }

    public JLabel getnivelacademico() {
        return jLabel_nivelacademico;
    }

    public JLabel getotrotelefono() {
        return jLabel_otrotelefono;
    }

    public JLabel getotrotitulo() {
        return jLabel_otrotitulo;
    }

    public JLabel getparroquia() {
        return jLabel_parroquia;
    }

    public JLabel getprimerapellido() {
        return jLabel_primerapellido;
    }

    public JLabel getprimernombre() {
        return jLabel_primernombre;
    }

    public JLabel getsegundoapellido() {
        return jLabel_segundoapellido;
    }

    public JLabel getsegundonombre() {
        return jLabel_segundonombre;
    }

    public JLabel gettelefono() {
        return jLabel_telefono;
    }

    public JLabel gettituloobtenido() {
        return jLabel_tituloobtenido;
    }

    public JTextArea getdireccion() {
        return jTextArea_direccion;
    }

    public JLabel getgruposanguineo() {
        return jLabel_gruposanguineo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel_foto = new javax.swing.JLabel();
        jLabel_primernombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_segundonombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_primerapellido = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_segundoapellido = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel_cedula = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel_fechanacimiento = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel_lugarnacimiento = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel_estadocivil = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel_genero = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel_nivelacademico = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel_tituloobtenido = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel_otrotitulo = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel_telefono = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel_otrotelefono = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel_gruposanguineo = new javax.swing.JLabel();
        jLabel_correo = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel_estado = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel_municipio = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel_parroquia = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_direccion = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INFORACIÓN");
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMACIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 526, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 680, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_foto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 160, 160));

        jLabel_primernombre.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_primernombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_primernombre.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_primernombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 310, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("- PRIMER NOMBRE:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jLabel5.setBackground(new java.awt.Color(249, 249, 249));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 20));

        jLabel_segundonombre.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_segundonombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_segundonombre.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_segundonombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 310, 20));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("- SEGUNDO NOMBRE:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 20));

        jLabel_primerapellido.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_primerapellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_primerapellido.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_primerapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 310, 20));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("- PRIMER APELLIDO:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel9.setBackground(new java.awt.Color(249, 249, 249));
        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 490, 20));

        jLabel_segundoapellido.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_segundoapellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_segundoapellido.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_segundoapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 310, 20));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setText("- SEGUNDO APELLIDO:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel14.setOpaque(true);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 490, 20));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setText("- CÉDULA DE IDENTIDAD:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jLabel_cedula.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_cedula.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_cedula.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 310, 20));

        jLabel17.setBackground(new java.awt.Color(249, 249, 249));
        jLabel17.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel17.setOpaque(true);
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 490, 20));

        jLabel_fechanacimiento.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_fechanacimiento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_fechanacimiento.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_fechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 310, 20));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel19.setText("- FECHA DE NACIMIENTO:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel20.setOpaque(true);
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 490, 20));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel21.setText("- LUGAR DE NACIMIENTO:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jLabel_lugarnacimiento.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_lugarnacimiento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_lugarnacimiento.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_lugarnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 310, 20));

        jLabel23.setBackground(new java.awt.Color(249, 249, 249));
        jLabel23.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel23.setOpaque(true);
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 20));

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel24.setText("- ESTADO CIVIL:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        jLabel_estadocivil.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_estadocivil.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_estadocivil.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_estadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 310, 20));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel26.setOpaque(true);
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 490, 20));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel27.setText("- GENERO:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jLabel_genero.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_genero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_genero.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 310, 20));

        jLabel29.setBackground(new java.awt.Color(249, 249, 249));
        jLabel29.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel29.setOpaque(true);
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 490, 20));

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel30.setText("- NIVEL ACADEMICO:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel_nivelacademico.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_nivelacademico.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_nivelacademico.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_nivelacademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 310, 20));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel32.setOpaque(true);
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 490, 20));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel33.setText("- TITULO OBTENIDO:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel_tituloobtenido.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_tituloobtenido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_tituloobtenido.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_tituloobtenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 310, 20));

        jLabel35.setBackground(new java.awt.Color(249, 249, 249));
        jLabel35.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel35.setOpaque(true);
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 490, 20));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel36.setText("- OTRO TITULO:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel_otrotitulo.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_otrotitulo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_otrotitulo.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_otrotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 310, 20));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel38.setOpaque(true);
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 490, 20));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel39.setText("- TELEFONO:");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        jLabel_telefono.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_telefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_telefono.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 310, 20));

        jLabel41.setBackground(new java.awt.Color(249, 249, 249));
        jLabel41.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel41.setOpaque(true);
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 490, 20));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel42.setText("- OTRO TELEFONO:");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        jLabel_otrotelefono.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_otrotelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_otrotelefono.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_otrotelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 310, 20));

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel44.setOpaque(true);
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 490, 20));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel46.setText("- GRUPO SANGUINEO:");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel45.setText("- CORREO:");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        jLabel_gruposanguineo.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_gruposanguineo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_gruposanguineo.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_gruposanguineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 310, 20));

        jLabel_correo.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_correo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_correo.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 310, 20));

        jLabel47.setBackground(new java.awt.Color(249, 249, 249));
        jLabel47.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel47.setOpaque(true);
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 490, 20));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel48.setText("- DIRECCIÓN:");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 20));

        jLabel51.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel51.setText("- ESTADO:");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 20));

        jLabel_estado.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_estado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_estado.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 310, 20));

        jLabel53.setBackground(new java.awt.Color(249, 249, 249));
        jLabel53.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel53.setOpaque(true);
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 490, 20));

        jLabel54.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel54.setText("- MUNICIPIO:");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 20));

        jLabel_municipio.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_municipio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_municipio.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 310, 20));

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel56.setOpaque(true);
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 490, 20));

        jLabel57.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel57.setText("- PARROQUIA:");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 20));

        jLabel_parroquia.setBackground(new java.awt.Color(0, 0, 51));
        jLabel_parroquia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_parroquia.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jLabel_parroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 310, 20));

        jLabel59.setBackground(new java.awt.Color(249, 249, 249));
        jLabel59.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel59.setOpaque(true);
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 490, 20));

        jTextArea_direccion.setColumns(20);
        jTextArea_direccion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextArea_direccion.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea_direccion.setLineWrap(true);
        jTextArea_direccion.setRows(5);
        jTextArea_direccion.setWrapStyleWord(true);
        jTextArea_direccion.setBorder(null);
        jScrollPane2.setViewportView(jTextArea_direccion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 310, -1));

        jTabbedPane1.addTab("DATOS PERSONALES", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 690, 560));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8_no_16px.png"))); // NOI18N
        jLabel49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel49MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVerPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVerPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVerPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVerPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_cedula;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_estado;
    private javax.swing.JLabel jLabel_estadocivil;
    private javax.swing.JLabel jLabel_fechanacimiento;
    private javax.swing.JLabel jLabel_foto;
    private javax.swing.JLabel jLabel_genero;
    private javax.swing.JLabel jLabel_gruposanguineo;
    private javax.swing.JLabel jLabel_lugarnacimiento;
    private javax.swing.JLabel jLabel_municipio;
    private javax.swing.JLabel jLabel_nivelacademico;
    private javax.swing.JLabel jLabel_otrotelefono;
    private javax.swing.JLabel jLabel_otrotitulo;
    private javax.swing.JLabel jLabel_parroquia;
    private javax.swing.JLabel jLabel_primerapellido;
    private javax.swing.JLabel jLabel_primernombre;
    private javax.swing.JLabel jLabel_segundoapellido;
    private javax.swing.JLabel jLabel_segundonombre;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JLabel jLabel_tituloobtenido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea_direccion;
    // End of variables declaration//GEN-END:variables
}
